[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate"]
    type = "git-repo"
    url = "https://github.com/Pilaton/OhMyZsh-full-autoupdate.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate".clone]
        args = ["--depth=1"]
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-autosuggestions".clone]
        args = ["--depth=1"]
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-completions".clone]
        args = ["--depth=1"]
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting".clone]
        args = ["--depth=1"]
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/themes/powerlevel10k".clone]
        args = ["--depth=1"]