[".oh-my-zsh"]
  refreshPeriod   = "168h"
  stripComponents = 1
  type            = "archive"
  url             = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
[".config/oh-my-zsh/plugins/fzf-tab"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/Aloxaf/fzf-tab.git"
  [".config/oh-my-zsh/plugins/fzf-tab".clone]
    args = ["--depth=1"]
[".config/oh-my-zsh/plugins/zsh-autosuggestions"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/zsh-users/zsh-autosuggestions.git"
  [".config/oh-my-zsh/plugins/zsh-autosuggestions".clone]
    args = ["--depth=1"]
[".config/oh-my-zsh/plugins/zsh-completions"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/zsh-users/zsh-completions.git"
  [".config/oh-my-zsh/plugins/zsh-completions".clone]
    args = ["--depth=1"]
[".config/oh-my-zsh/plugins/zsh-history-substring-search"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/zsh-users/zsh-history-substring-search.git"
  [".config/oh-my-zsh/plugins/zsh-history-substring-search".clone]
    args = ["--depth=1"]
[".config/oh-my-zsh/plugins/zsh-syntax-highlighting"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  [".config/oh-my-zsh/plugins/zsh-syntax-highlighting".clone]
    args = ["--depth=1"]
[".config/oh-my-zsh/themes/powerlevel10k"]
  refreshPeriod = "168h"
  type          = "git-repo"
  url           = "https://github.com/romkatv/powerlevel10k.git"
  [".config/oh-my-zsh/themes/powerlevel10k".clone]
    args = ["--depth=1"]
