tap "derailed/k9s"
tap "dotenv-org/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "infisical/get-cli"
tap "lyraphase/pcloud"
tap "spicetify/tap"
tap "yqrashawn/goku"
# Run your GitHub Actions locally
brew "act"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Download with resuming and segmented downloading
brew "aria2"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq", restart_service: true
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Command-line tool to interact with exercism.io
brew "exercism"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Git extension for versioning large files
brew "git-lfs"
# Kubernetes package manager
brew "helm"
# API Support for your favorite torrent trackers
brew "jackett", restart_service: true
# Lightweight and flexible command-line JSON processor
brew "jq"
# Postgres C API library
brew "libpq", link: true
# Library for USB device access
brew "libusb"
# Replacement for ls, cp and other commands for object storage
brew "minio-mc"
# Modern Linker
brew "mold"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package management made easy
brew "pixi"
# Manage compile and link flags for libraries
brew "pkg-config"
# Python package management tool
brew "poetry"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Rust toolchain installer
brew "rustup-init"
# Cross-shell prompt for astronauts
brew "starship"
# Programmatically correct mistyped console commands
brew "thefuck"
# Library to create, extract, and modify Windows Imaging files
brew "wimlib"
# UNIX shell (command interpreter)
brew "zsh"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s"
# Sync .env files
brew "dotenv-org/brew/dotenv-vault"
# The official Infisical CLI
brew "infisical/get-cli/infisical"
# Application launcher and productivity software
cask "alfred"
# Local-first and end-to-end encrypted notes app
cask "anytype"
# Application uninstaller
cask "appcleaner"
# Manage team projects and tasks
cask "asana"
# Web browser focusing on privacy
cask "brave-browser"
# Bittorrent client
cask "c0re100-qbittorrent"
# E-books management software
cask "calibre"
# App to build and share containerised applications and microservices
cask "docker"
# Online diagram software
cask "drawio"
# YouTube player focusing on privacy
cask "freetube"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# File system integration
cask "macfuse"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# File manager
cask "path-finder"
# Client for the pCloud virtual cloud storage service
cask "pcloud-drive"
# VPN client focusing on security
cask "protonvpn"
# Instant messaging application focusing on security
cask "signal"
# Knowledge management for organisations
cask "slab"
# Customise mouse buttons, wheels and cursor speed
cask "steermouse"
# Open-source media center
cask "stremio"
# Native GUI tool for relational databases
cask "tableplus"
# Remote access and connectivity software focused on security
cask "teamviewer"
# Unpacks archive files
cask "the-unarchiver"
# Web browser focusing on security
cask "tor-browser"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
vscode "aaron-bond.better-comments"
vscode "af4jm.vscode-icalendar"
vscode "ajmnz.prisma-import"
vscode "alefragnani.project-manager"
vscode "alexcvzz.vscode-sqlite"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "antfu.unocss"
vscode "artdiniz.quitcontrol-vscode"
vscode "astro-build.astro-vscode"
vscode "battlebas.kivy-vscode"
vscode "beardedbear.beardedtheme"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "clinyong.vscode-css-modules"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-database-client2"
vscode "darkriszty.markdown-table-prettify"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "dnicolson.binary-plist"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "fabiospampinato.vscode-diff"
vscode "foxundermoon.shell-format"
vscode "fredwangwang.vscode-hcl-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.hcl"
vscode "hediet.vscode-drawio"
vscode "irongeek.vscode-env"
vscode "jgclark.vscode-todo-highlight"
vscode "jock.svg"
vscode "kavish.hex-to-hsl"
vscode "kbysiec.vscode-go-to-mdn"
vscode "liviuschera.noctis"
vscode "luquedaniel.languague-renpy"
vscode "meganrogge.template-string-converter"
vscode "mgmcdermott.vscode-language-babel"
vscode "mikeburgh.xml-format"
vscode "mikestead.dotenv"
vscode "mikoz.autoflake-extension"
vscode "mindaro-dev.file-downloader"
vscode "mrmlnc.vscode-scss"
vscode "mrorz.language-gettext"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "mvllow.rose-pine"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "richie5um2.vscode-sort-json"
vscode "rust-lang.rust-analyzer"
vscode "ryu1kn.partial-diff"
vscode "ryuta46.multi-command"
vscode "serayuzgur.crates"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "stackbreak.comment-divider"
vscode "stkb.rewrap"
vscode "sumneko.lua"
vscode "swellaby.rust-pack"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "tomoki1207.pdf"
vscode "tyriar.sort-lines"
vscode "vscodevim.vim"
vscode "xshrim.txt-syntax"
vscode "yrm.type-challenges"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "zengxingxin.sort-js-object-keys"
