{1}{1}25.000
{937}{1019}Oh God! Bills, bills, bills.
{1024}{1172}One is born, one runs up bills, one dies.|What have I got to show for it? Nothing.
{1177}{1273}A butler's uniform|and a slightly effeminate hairdo.
{1278}{1443}Sometimes I feel like a pelican - whichever way I|turn, I've still got an enormous bill in front of me.
{1479}{1583}Pass the biscuit barrel.|Let's see what's in the kitty shall we?
{1636}{1716}Nine pence. Oh God, what are we going to do?
{1721}{1834}Don't worry Mr B,|I have a cunning plan to solve the problem.
{1839}{1931}Let us not forget, that you tried to solve|the problem of your mother's low ceiling
{1936}{1990}by cutting off her head.
{1995}{2130}But this is a really good one.|You become a dashing highwayman,
{2135}{2237}then you can pay all your bills and, on top of that,|everyone'll want to sleep with you.
{2242}{2332}Baldrick, I could become a prostitute|and pay my bills,
{2337}{2419}then everyone would want to sleep with me,|but I do consider certain professions beneath me.
{2424}{2562}And I fail to see why a thief should be idolised,|just because he has a horse between his legs.
{2567}{2720}My favourite's the Shadow. What a man! They say|he's halfway to being the new Robin Hood.
{2725}{2795}- Why only halfway?|- Well, he steals from the rich,
{2800}{2879}but he hasn't got round|to giving it to the poor yet.
{2884}{2955}Look, I've got a poster of him.
{2960}{3032}I have no desire to get hung|for wearing a silly hat.
{3037}{3161}If I want to get rich quick, all I have to do|is go upstairs and ask Prince Fathead for a rise.
{3166}{3206}(BELL RINGS)
{3211}{3269}The bank's open.
{3354}{3463}Good morning, sir.|May I say how immensely rich you're looking?
{3468}{3540}Was there anything you wanted? Anything at all?
{3545}{3626}Yes, I was wondering|if you could lend me a bit of cash.
{3631}{3695}But of course, sir, I... Cash?
{3700}{3796}Yes, I'm rotten stinking stoning stinking broke.
{3801}{3845}What about the 5,000 pounds
{3850}{3944}that Parliament voted you last week|to drink yourself to death with?
{3949}{4109}All gone I'm afraid. You see, I've discovered this|terrifically fun new game. It's called "cards".
{4114}{4226}You sit round the table with your friends,|and you deal out five "cards" each,
{4231}{4343}and then the object of the game is to|give away all your money as quickly as possible.
{4348}{4411}- Do you know it?|- Vaguely, sir, yes.
{4416}{4456}All the chaps say I'm terrific at it.
{4461}{4563}I was very bad at it. I always seemed to end up|with more money than I started with.
{4568}{4651}It's all down to practice.|I'm a natural apparently.
{4656}{4719}The only drawback|is that it's pretty damned expensive.
{4724}{4783}So I was wondering|if you could lend me a couple of hundred.
{4788}{4924}I'm afraid that's impossible. I'm as poor as a|church mouse that's just had an enormous tax bill
{4929}{5027}on the very day his wife ran off|with another mouse, taking all the cheese.
{5032}{5125}- What am I going to do?|- It's a difficult one.
{5130}{5240}Let's see now. You can't borrow money,|you're not going to inherit any money
{5245}{5339}and obviously you can't earn money.
{5344}{5497}Sir, drastic situations call for drastic measures.|If you can't make money, you'll have to marry it.
{5502}{5553}Marry? Never!
{5558}{5623}I'm a gay bachelor, Blackadder.
{5628}{5732}I'm a roarer, a rogerer, a gorger and a puker.
{5737}{5831}I can't marry.|I'm young, I'm firm buttocked, I'm...
{5836}{5907}- Broke?|- Well, yes, I suppose so.
{5912}{6041}And don't forget, sir, that the modern Church|smiles on roaring and gorging within wedlock,
{6046}{6128}and indeed rogering is keenly encouraged.
{6133}{6181}And the puking?
{6186}{6290}I believe still very much down to the|conscience of the individual churchgoer.
{6295}{6361}Well, tally-ho then, Blackadder.|Yes, you fix it up.
{6366}{6477}You know the kind of girls I like,|they've got to be lovers, laughers, dancers...
{6482}{6536}And bonkers.
{6541}{6579}That goes without saying.
{6602}{6691}- Oh God!|- Something wrong, Mr B?
{6696}{6773}I can't find a single person|suitable to marry the prince.
{6778}{6844}Please, keep trying, I love a royal wedding.
{6849}{6961}The excitement, the crowds, the souvenir mugs,
{6966}{7026}the worrying about|whether the bride's lost weight.
{7066}{7228}Unlikely with this lot. If the prince had stipulated|"must weigh a quarter of a ton" we'd be laughing.
{7233}{7348}Of the 262 princesses in Europe,|165 are over 80, they're out,
{7353}{7446}47 are under 10, they're out,|and 39 are mad.
{7451}{7491}They sound ideal.
{7496}{7617}They would be if they hadn't all got married|last week in Munich to the same horse.
{7622}{7693}- Which leaves us with two.|- And what about them?
{7698}{7793}Well, there's Grand Duchess Sophia of Turin -|we'll never get her to marry him.
{7798}{7883}- Why not?|- Because she's met him.
{7935}{7974}Which leaves?
{7979}{8105}- Caroline of Brunswick.|- What's wrong with her?
{8110}{8213}Get more coffee! Change it! Take me roughly|from behind! No, not like that, like this!
{8218}{8299}Trousers off! Tackle out! Walk the dog!|Where's my presents?
{8304}{8382}Which one do you want me to do first?
{8387}{8547}No, that's what Caroline's like. She is famous|for having the worst personality in Germany.
{8552}{8642}And as you can imagine,|that's up against some pretty stiff competition.
{8647}{8767}- So you're stuck then.|- Yes, I'm afraid I am.
{8772}{8876}Unless...|Pass me the paper, Baldrick, quick.
{8921}{9001}Why has half the front page been cut out?
{9006}{9069}- I don't know.|- You do know, don't you?
{9074}{9121}Yes.
{9126}{9202}You've been cutting out the cuttings|about the elusive Shadow
{9207}{9273}to put in your|highwayman's scrapbook, haven't you?
{9278}{9456}I can't help it, Mr B. His life is so dark and|shadowy and full of fear and trepidation.
{9461}{9570}So is going to the toilet in the middle of the|night, but you don't keep a scrapbook on it.
{9575}{9609}I do.
{9614}{9751}Now, let's see, society pages.|You see, it needn't necessarily be a princess.
{9756}{9825}All the Prince wants|is someone pretty and rich.
{9830}{9877}Oh dear, that rules me out then.
{9882}{10028}Now, let me see.|"Beau Brummel in purple pants probe."
{10033}{10140}"King talks to tree. Phew! What a loony."
{10145}{10242}God, the Times has really gone downhill recently.
{10247}{10311}Aha! Listen to this:
{10316}{10395}"Mysterious northern beauty, Miss Amy Hardwood,
{10400}{10502}comes to London|and spends flipping great wodges of cash!"
{10507}{10575}That's our baby!
{10601}{10723}I don't know why I'm bothering to get dressed.|As soon as I get to the Naughty Hellfire Club
{10728}{10813}I'll be de-bagged|and radished for non-payment of debts.
{10818}{10885}- Radished, sir?|- They pull your britches down.
{10890}{10996}- And push a large radish right up your...|- Yes, all right, sir!
{11022}{11087}There's no need to hammer it home.
{11092}{11186}- As a matter of fact they do often have to...|- No! No!
{11191}{11312}- Your money worries are over, sir.|- Well, hurrah for that.
{11317}{11448}I have found you a bride. Her name is Amy,|daughter of the noted industrialist, Mr Hardwood.
{11453}{11530}Dammit, Blackadder,|you know I loathe industrialists.
{11535}{11631}Sad, balding, little proles|in their damn-your-eyes waistcoats.
{11636}{11708}All puffed up because they know where|to put the legs on a pair of trousers.
{11713}{11842}Believe me, sir, these people are the future.|This man probably owns half of Lancashire.
{11847}{11949}His family's got more mills|than you've got brain cells.
{11985}{12040}- How many mills?|- Seven, sir.
{12045}{12107}Quite a lot of mills then.
{12112}{12201}He has patented a machine called|"The Ravelling Nancy".
{12206}{12284}- What does it do?|- It ravels cotton, sir.
{12289}{12347}- What for?|- That I cannot say, sir.
{12352}{12475}I am one of these people who are quite happy|to wear cotton, but have no idea how it works.
{12480}{12523}She is also a beauty, sir.
{12528}{12631}Well, if she's gonna be my bird, she'd better be.|Right, so what's the plan?
{12636}{12735}I thought I could take her a short note|expressing your honourable intentions.
{12740}{12841}Yes, yes, I think so too.|All right then, take this down.
{12846}{12958}"From His Royal Highness the Prince of Wales|to Miss Amy Hardwood.
{12963}{13067}Tally-ho, my fine saucy young trollop.|Your luck's in.
{13072}{13185}Trip along here with all your cash,|and some naughty night attire,
{13190}{13346}and you'll be staring at my bedroom ceiling|from now till Christmas, you lucky tart.
{13351}{13497}Yours with the deepest respect etc, signed George.|P.S. Woof! Woof!"
{13502}{13608}- Well, what do you think?|- It's very moving, sir.
{13613}{13688}Would you mind if I changed|just one tiny aspect of it?
{13693}{13750}- Which one?|- The words.
{13773}{13834}I'll leave the details to you, Blackadder.
{13839}{13960}Just make sure she knows I'm all man,|with a bit of animal thrown in.
{13965}{14018}Certainly, sir.
{14041}{14140}From his Royal Highness the Prince of Wales|to Miss Amy Hardwood:
{14145}{14295}"The upturned tilt of your tiny wee nosy,|smells as sweet as a great big posy."
{14327}{14437}- Fanciful stuff, madam, but from the heart.|- He says my nosy is tiny?
{14442}{14485}And wee, madam.
{14490}{14639}Well, he must be an awful clever clogs,|because you see, my nosy is tiny,
{14644}{14750}and so wee, that I sometimes think|the pixies gave it to me.
{14876}{15019}He continues:|"Oh, Lady Amy, Queen of all your sex."
{15024}{15100}I apologise for the word, madam,|but Prince George is a man of passion.
{15105}{15191}Don't worry,|I can get pretty cross myself sometimes.
{15251}{15415}I've heard a teensy rumour that the Prince|has the manners of a boy-cow's dingle dangle.
{15420}{15510}- What do you have to say to that?|- That is a lie, madam.
{15515}{15681}Prince George is shy and just pretends to be|bluff and crass and unbelievably thick and gittish,
{15686}{15802}whilst deep down he is a soft little marshmallowy,|pigletty type of creature.
{15807}{15965}Oh, I'm so glad.|You see, I'm a delicate tiny thing myself,
{15970}{16058}weak and silly and like a little fluffy rabbit.
{16063}{16150}So I could never marry a horrible heffalump,|or I might get squished.
{16195}{16262}Tell me,|when can I meet the lovely Prince?
{16267}{16323}You want to meet him?
{16328}{16405}If we're going to get married|I think I probably ought to.
{16410}{16553}I know! Tell him to come and serenade me|tonight. I'll be on my balcony in my jim-jams.
{16558}{16613}Certainly, madam.
{16618}{16689}Eh up! Who's this big girl's blouse, then?
{16694}{16822}Father, this is Mr Blackadder, he's come|a-wooing from the Prince.
{16827}{16913}- You have a beautiful and charming daughter.|- Indeed I do.
{16918}{17001}I love her more than any pig,|and that's saying summat!
{17006}{17063}It certainly is.
{17068}{17170}And let me tell you, I'd no more place her|in the hands of an unworthy man
{17175}{17281}than I'd place my John Thomas|in the hands of a lunatic with a pair of scissors.
{17326}{17391}An attitude that does you credit, sir.
{17396}{17519}I'd rather paint my bottom blue|than give her to a man who didn't love her.
{17524}{17596}What self-respecting father could do more?
{17601}{17711}On the other hand, if he's a prince,|he can have her for ten bob and a pickled egg.
{17716}{17819}- I can see where your daughter gets her wit, sir.|- I thank you.
{17824}{17925}Although where she gets her good looks|and charm is perhaps more of a mystery.
{17930}{18080}- No one ever made money out of good looks.|- You obviously haven't met Lady Hamilton, sir.
{18149}{18237}I tell you, Baldrick,|I'm not looking forward to this evening.
{18242}{18323}Trying to serenade a light fluffy bunny of a girl
{18328}{18434}in the company of an arrogant half German yob|with a mad dad.
{18439}{18524}- He is the Prince of Wales.|- Have you ever been to Wales, Baldrick?
{18529}{18656}- No, but I've often thought I'd like to.|- Well don't, it's a ghastly place.
{18661}{18814}Huge gangs of tough sinewy men roam the valleys|terrifying people with their close harmony singing.
{18866}{18992}You need half a pint of phlegm in your throat|just to pronounce the place-names.
{19023}{19150}Never ask for directions in Wales, Baldrick, you'll|be washing spit out of your hair for a fortnight.
{19155}{19293}- So being Prince of it isn't considered a plus?|- I fear not, no.
{19298}{19402}But the crucial thing is that they must never|be left alone together before the marriage.
{19407}{19504}- Isn't that a bit unfair on her?|- It's not exactly fair on him either.
{19509}{19595}The girl is wetter|than a haddock's bathing costume.
{19600}{19660}But you know, Baldrick, the world isn't fair.
{19665}{19739}If it was,|things like this wouldn't happen, would they?
{19853}{19901}What's the plan?
{19906}{20069}Shin up the drain and ask her if she'll take|delivery of a consignment of German sausage?
{20074}{20210}No, sir.|As we rehearsed: poetry first, sausage later.
{20215}{20317}Right. So, what do you think?|"Harold the Horny Hunter" should do the trick.
{20322}{20355}Remind me of it, sir.
{20360}{20447}"Harold the Horny hunter,|had an enormous horn."
{20452}{20581}It is absolutely excellent, sir.|However, might I suggest an alternative?
{20586}{20654}"Lovely little dumpling, how in love I am.
{20659}{20751}Let me be your shepherdkins,|you can be my lamb."
{20756}{20873}I think we'll be very lucky if she doesn't just|come out onto the balcony and vomit over us.
{20878}{20919}Let's give it a whirl.
{20924}{21083}Just stand right here, sir.|Call for her romantically.
{21088}{21205}(GEORGE SHOUTS): Oy! Come on out here,|you rollicking trolloping sauce bottle!
{21210}{21288}- (AMY): George?|- (GEORGE): Woof! Woof!
{21308}{21351}Is that you?
{21356}{21476}Yes, 'tis I, your gorgeous little love bundle.
{21481}{21640}Oh, George, I think you must be the snuggly|wuggliest lambkin in the whole of toy-land.
{21669}{21713}Yucch!
{21718}{21753}What was that?
{21758}{21880}Nothing, there was just|a little fly in my throaty. Yucch, yucch...
{21885}{21999}Do you want a hanky wanky|to gob the phlegmy wemmy woo into?
{22004}{22051}Phwoah! Crikey!
{22056}{22134}What was that?|Is there someone down there with you?
{22139}{22219}No, it was just the wind|whistling through the trees
{22224}{22371}and making a noise that sounded like|"phwoaaaah crikeeeeeey".
{22392}{22549}Oh, joy!|Then come, Prince Cuddly Kitten, climb up my ivy.
{22554}{22611}Sausage time!
{22616}{22709}- There is someone down there with you!|- Oh my God, so there is.
{22714}{22823}- A filthy intruder spying on our love.|- Hit him, George, hit him!
{22828}{22876}Very well.|Would you mind screaming, Your Highness.
{22881}{22951}Take that! And that!
{22956}{23004}And that!
{23009}{23073}Oh, you're so brave!
{23078}{23181}And I'm so worn out with all the excitement|that I'd better go sleepy bobos,
{23186}{23261}otherwise I'll be all cross in the morning.
{23266}{23368}- Nighty-night, Georgy Porgy!|- Nighty-wighty, Amy Wamy.
{23393}{23454}I think it worked, sir.
{23459}{23580}In the morning I shall go in and ask her father,|you go out and start spending his money.
{23585}{23660}I can't stand meanness|when it comes to wedding presents.
{23665}{23737}- And well done, sir, you were brilliant.|- Was I?
{23742}{23833}- But I'm in agony!|- Well, that's love for you.
{23838}{23952}Sir, I come as emissary of the Prince of Wales|with the most splendid news.
{23957}{24115}- He wants your daughter Amy for his wife.|- Well his wife can't have her!
{24120}{24190}Outrageous, sir,|to come here with such a suggestion!
{24195}{24321}Mind, sir, or I shall take off my belt|and by thunder me trousers will fall down!
{24326}{24435}No, sir, you misunderstand.|He wants to marry your lovely daughter.
{24440}{24536}Ah, ah... Can it be possibly true?
{24541}{24623}Surely love has never crossed|such boundaries of class?
{24628}{24665}What about you and Mum?
{24670}{24740}I grant thee,|when I first met her, I was the farmer's son
{24745}{24815}and she was just the lass who ate the dung,|but that was an exception.
{24820}{24867}And Aunty Dot and Uncle Ted.
{24872}{24934}Yes, he was a pig poker|and she was the Duchess of Argyle, but...
{24939}{24999}And Aunty Ruth was a milkmaid|and Uncle Isiah...
{25004}{25108}The Pope!|Yes, yes, all right. Don't argue.
{25113}{25251}Suffice to say if you marry, we need never be|poor or hungry again. Sir, we accept.
{25256}{25363}So obviously you'll be wanting|an enormous ceremony... What did you say?
{25368}{25502}Well, obviously, now we're marrying quality,|we'll never be poor or hungry again.
{25507}{25600}- Are you poor and hungry at the moment?|- Oh yes!
{25605}{25684}We've been living off lard butties|for five years now.
{25689}{25784}I'm so poor|I use my underpants for drying dishes.
{25789}{25837}- So you're skint?|- Aye.
{25842}{25900}In that case, the wedding's off. Good day.
{25905}{26015}But what about George's lovey-wovey poems|that won my hearty-wearty?
{26020}{26145}All writteny-witteny by me-wee|I'm afraidy-waidy. Goodbye.
{26213}{26347}Sir, you know I told you to go out and spend a lot|of money on wedding presents, well apparent...
{26417}{26451}Yes?
{26477}{26518}Nothing.
{26602}{26722}Crisis, Baldrick, crisis!|No marriage, no money, more bills!
{26727}{26846}For the first time I've decided to follow a|suggestion of yours. Saddle Prince George's horse.
{26851}{26909}You're not becoming a highwayman, are you?
{26914}{27027}No, I'm auditioning for the part of Arnold the Bat|in Sheridan's new comedy.
{27032}{27092}Oh, that's all right then.
{27097}{27163}Baldrick, have you no idea what irony is?
{27168}{27280}Yeah, it's like goldy and bronzy,|only it's made of iron.
{27285}{27392}Never mind, never mind.|Just saddle the Prince's horse.
{27397}{27512}That'll be difficult, he wrapped her|round that gas lamp in the Strand last night.
{27517}{27550}Saddle my horse then.
{27555}{27641}What do you think you've been eating|for the last two months?
{27646}{27711}Well go out into the street and hire me a horse.
{27716}{27811}Hire you a horse? For ninepence?|On Jewish New Year in the rain?
{27816}{27919}A bare fortnight after the dreaded horse plague|of Old London Town?
{27924}{28060}With the blacksmith's strike in its fifteenth week|and the Dorset Horse-Fetishists fair tomorrow?
{28065}{28195}Right, well get this on then.|It looks as though you could do with the exercise.
{28271}{28355}Honestly, Papa. Ever since mother died|you've tried to stop me growing up.
{28360}{28471}I'm not a little girl, I'm a grown woman.|In fact I might as well tell you now, Papa:
{28476}{28572}I'm pregnant, and I'm an opium fiend,|and I'm in love with a poet called Shelley,
{28577}{28695}who's a famous whoopsy.|And mother didn't die, I killed her!
{28700}{28776}Well, never mind.
{28785}{28850}(GUNSHOT)|(BLACKADDER): Stand and deliver!
{28855}{29003}Oh no - disaster.|It's the Shadow - we're doomed, doomed.
{29032}{29195}Good evening, Duke, and the lovely|Miss Cheapside. Your cash-bags, please.
{29200}{29283}You'll never get away with this!|You'll be caught and damn well hung.
{29288}{29332}- I think he looks...|- Madam, please.
{29337}{29453}Not the jest about me looking|pretty well hung already, we have no time.
{29458}{29518}- Now, sir, turn out your pockets.|- Never, sir!
{29523}{29617}A man's pockets are his own private kingdom.|I'll protect them with my life.
{29622}{29748}Got something embarrassing in there, have you?|A particularly repulsive handkerchief, hm?
{29753}{29900}One of those fellows who has a big blow|and then doesn't change it for a week?
{29905}{29990}- Aha!|- Highwayman, I also have a jewel.
{29995}{30129}I fear however, that I have placed it here,|beneath my petticoat, for protection.
{30134}{30193}Well in that case I think I'll leave it.
{30198}{30305}I'm not sure I fancy the idea of a jewel|that's been in someone's pants.
{30310}{30382}A single kiss of those soft lips is all I require.
{30387}{30418}Never, sir!
{30423}{30537}A man's soft lips are his own private kingdom,|I shall defend them with my life.
{30542}{30598}I'm not talking to you, grandad.
{30696}{30796}Oh, I am overcome. Take me with you|to live the life of the wild rogue,
{30801}{30895}cuddling under haystacks|and making love in the branches of tall trees.
{30900}{31031}Sadly I must decline - I fear my horse would|collapse with you on top of him as well as me.
{31036}{31090}I could try.
{31172}{31263}- No, Quicksilver, you couldn't.|- That's not fair then.
{31268}{31368}I had you on my back for ten miles,|and I don't even get a kiss out of it.
{31373}{31422}All right, very well then...
{31479}{31543}- All fair now?|- Not really, no.
{31548}{31633}No pleasing some horses. Hi ho, Quicksilver!
{31681}{31755}Papa, you did nothing to defend my honour.
{31760}{31855}Oh, shut your face, you pregnant junkie fag-hag.
{31875}{31969}Well, Baldrick, a good night's work, I think.
{31974}{32073}It's time to divide the loot. I think|it's only fair that we should share it equally.
{32078}{32183}Which I suppose is highwayman's talk|for you get the cash, I get the snotty hankie.
{32188}{32283}No, we did this robbery together,|so you get half the cash.
{32288}{32323}Thank you, Mr B.
{32328}{32469}This robbery, on the other hand, I'm doing alone.|Hand it over, your money or your life.
{32474}{32614}- There you see, all fair and above board.|- As long as I haven't been cheated I don't mind.
{32619}{32715}Hands up! I'm the Shadow, and I never miss.
{32720}{32764}Oh no.
{32769}{32901}- You, the one that looks like a pig.|- He's talking to you, Baldrick.
{32906}{32964}Scedaddle!
{33015}{33092}So... who have we here.
{33173}{33288}A well set up fellow indeed. Sir, a kiss.
{33293}{33434}- Sorry, I'm not sure I heard that correctly.|- Oh dear. Maybe your ears need unblocking.
{33439}{33591}Oh, a kiss! Of course. Then perhaps a light supper,|some dancing, who knows where it might lead.
{33647}{33726}- Good Lord, it's you!|- Of course!
{33731}{33784}- But your voice?|- Clever, isn't it?
{33789}{33875}- Does your father know you're out?|- He had to go.
{33880}{33968}- You mean he's dead?|- Yes. Dead as that squirrel.
{33973}{34034}Which squirrel?
{34039}{34086}(A SQUEAK, FOLLOWED BY A THUD)
{34111}{34169}Oh, that squirrel.
{34174}{34281}Of course! You killed him for ruining your chances|of marrying Prince George.
{34286}{34399}I despise the Prince.|Don't you know it's you I want.
{34404}{34515}I want a real man.|A man who can sew on a button.
{34520}{34597}A man who knows where the towels are kept.
{34602}{34730}And yes, I crave your fabulous sinewy body.
{34735}{34803}Well, you're only human.
{34808}{34857}Here's the plan, brown eyes,
{34862}{34975}you rob the Prince of everything he's got,|right down to the clothes he's standing in.
{34980}{35099}I'll get my stash and meet you here.|Then we run away to the West Indies.
{35104}{35171}Well, I don't know, I'll have to think about it.
{35176}{35305}I've thought about it, it's a brilliant plan.|See you here tomorrow.
{35361}{35410}Right, I'm off.
{35415}{35526}But what about the danger?|Look, the reward is going up day by day.
{35531}{35645}I laugh in the face of danger.|I drop ice-cubes down the vest of fear.
{35650}{35756}Things couldn't be better, Baldrick.|She'll get me abroad and make me rich.
{35761}{35859}Then I'll probably drop her|and get two hundred concubines to share my bed.
{35864}{35924}Wouldn't that be rather prickly?
{35987}{36059}Concubines, Baldrick, not porcupines.
{36064}{36132}I still can't believe you're leaving me behind.
{36137}{36247}Don't worry - when we're established on our|plantation in Barbados, I'll send for you.
{36252}{36385}No more sad little London for you, Balders.|You'll stand out in life as an individual.
{36390}{36499}- Will I?|- Of course, all the other slaves will be black.
{36504}{36639}Oh, Mr Blackadder, what's all this I hear|about you buying a bathing-costume
{36644}{36736}and forty gallons of coconut oil.|Are you going abroad then, sir?
{36741}{36891}- Yes, I'm off.|- Oh, sir, what a tragic end to all my dreams.
{36896}{36980}And I'd always hoped you would marry me
{36985}{37101}and that together|we might await the slither of tiny Adders.
{37106}{37269}Mrs M, if we were the last three humans on earth|I'd be trying to start a family with Baldrick.
{37397}{37497}Here I am, all packed and ready to go.
{37502}{37624}Darling, I'm so pleased to see you.|And I've got a little surprise for you.
{37629}{37722}Close your eyes and open your mouth.
{37727}{37803}Hand over the loot, goat brains.
{37808}{37948}Ha ha ha! I always said the bedrock of a good|relationship is being able to laugh together.
{37953}{38051}- Good. Well done. So, which way to Barbados?|- You're not going to Barbados.
{38056}{38159}Get away from the cart, Mr Slimy,|or I'll fill you so full of lead
{38164}{38249}we could sharpen your head and call you a pencil.
{38254}{38334}This is turning into a really rotten evening.
{38339}{38436}You'd better make the most of it - it's your last.
{38441}{38606}And it's a pity, because it's usually|against my principles to shoot dumb animals.
{38611}{38715}- Except squirrels?|- Yes. Bastards.
{38720}{38808}I hate them with their long tails|and their stupid twitchy noses.
{38920}{38993}I shall return at midnight to collect the loot -
{38998}{39134}when I'll fill you so full of holes|I could market you as a new English cheese.
{39139}{39187}(EVIL LAUGHTER)
{39233}{39312}Oh God, what a way to die.
{39317}{39404}Shot by a transvestite|on an unrealistic grassy knoll.
{39409}{39505}- Morning, Mr B.|- Baldrick!
{39510}{39608}Thank you for introducing me|to a genuinely new experience.
{39613}{39712}- What experience is that?|- Being pleased to see you.
{39717}{39818}- What are you doing here, you revolting animal?|- I've come for the Shadow's autograph.
{39823}{39921}- You know, I'm a great fan of the Shadow.|- Yes. Just untie me, Baldrick.
{39926}{40051}Has he gone? What a pity.|I wanted him to autograph my new poster.
{40056}{40126}Look, his reward's gone up|to ten thousand pounds.
{40131}{40263}Good Lord, ten thousand pounds -|that gives me an idea.
{40268}{40380}Take this cart-load of loot back to the palace|and meet me back here at midnight
{40385}{40506}with ten soldiers, a restless lynch-mob|and a small portable gallows.
{40580}{40628}Ha ha! Brekkers!
{40633}{40776}I could eat fourteen trays of it this morning|and still have room for a dolphin on toast.
{40781}{40854}Any particular reason|for this gluttonous levity, sir?
{40859}{40963}Well, what do you think, Blackadder?|I'm in love. I'm in love. I'm in love.
{40968}{41060}Oh, Amy, bless all ten of your tiny pinkies.
{41065}{41137}Now, let's see what's in the paper.
{41165}{41241}Oh my God! She's been arrested and hanged.
{41269}{41307}Really?
{41357}{41452}- It turns out she was a highwayman.|- These modern girls.
{41457}{41592}Apparently someone tipped off the authorities|and collected the ten thousand pounds reward.
{41597}{41702}What a greasy sneak.|If only I could get my hands on him.
{41707}{41838}- You can't trust anyone these days.|- It says here that she had an accomplice.
{41882}{41942}But they don't know who it was.
{41947}{42128}Oh, Amy, Amy, Amy, I shall never forget you.|Never ever never ever...
{42133}{42210}- Right, what's for breakfast?|- Kedgeree, sir.
{42215}{42344}Great. I didn't need to get married anyway.|I've got pots of money.
{42349}{42405}- Really?|- The most extraordinary thing happened.
{42410}{42531}I was a bit peckish during the night,|so I nipped downstairs to the biscuit barrel.
{42536}{42672}And do you know what I found inside?|Ten thousand pounds I never knew I had.
{42677}{42753}I've got so much money now|I don't know what to do with it.
{42758}{42865}- How about a game of cards, sir?|- Excellent idea!
{42890}{42965}Best watched using Open Subtitles MKV Player