

[data]
    nf_dev_dir="Dev/NosFuturs"
    ephemeral = false
    git_email = "11173924+CamilleHbp@users.noreply.github.com"
    git_name = "CamilleHBP"
    headless = false
    hostname = "camille-mbp"
    personal = true

[diff]
    exclude = ["scripts"]
    pager = "diff-so-fancy"

[edit]
    watch = true
    command = "code"
    args = ["--wait"]

[[textconv]]
    pattern = "**/*.plist"
    command = "plutil"
    args = ["-convert", "xml1", "-o", "-", "-"]